"""add pipeline_run and stage_trace tables

Revision ID: 245c694fed3d
Revises: 
Create Date: 2026-09-04 15:54:43.717083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245c694fed3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_lead_id'), 'pipeline_run', ['lead_id'], unique=False)
    op.create_table('stage_trace',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage_name', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=True),
    sa.Column('output_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_trace_run_id'), 'stage_trace', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_trace_run_id'), table_name='stage_trace')
    op.drop_table('stage_trace')
    op.drop_index(op.f('ix_pipeline_run_lead_id'), table_name='pipeline_run')
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
