"""add notification table

Revision ID: 5f3cbe979b96
Revises: 68de6a50cacb
Create Date: 2026-09-04 20:47:13.827690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3cbe979b96'
down_revision: Union[str, None] = '68de6a50cacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('outcome_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_link', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_lead_id'), 'notification', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notification_run_id'), 'notification', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_run_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_lead_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
