"""add review_queue_item table

Revision ID: 68de6a50cacb
Revises: 245c694fed3d
Create Date: 2026-09-04 17:44:52.890677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68de6a50cacb'
down_revision: Union[str, None] = '245c694fed3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('draft_intent_label', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_action', sa.String(length=16), nullable=True),
    sa.Column('corrected_intent_label', sa.String(length=64), nullable=True),
    sa.Column('state_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_item_lead_id'), 'review_queue_item', ['lead_id'], unique=False)
    op.create_index(op.f('ix_review_queue_item_run_id'), 'review_queue_item', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_item_run_id'), table_name='review_queue_item')
    op.drop_index(op.f('ix_review_queue_item_lead_id'), table_name='review_queue_item')
    op.drop_table('review_queue_item')
    # ### end Alembic commands ###
