"""add pipeline run list columns

Revision ID: 9217c457cc82
Revises: 5f3cbe979b96
Create Date: 2026-09-04 21:55:57.213259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9217c457cc82'
down_revision: Union[str, None] = '5f3cbe979b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_run', sa.Column('source_channel', sa.String(length=32), nullable=True))
    op.add_column('pipeline_run', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_run', 'confidence_score')
    op.drop_column('pipeline_run', 'source_channel')
    # ### end Alembic commands ###
